### ISSUE TITLE
Async execution yields wrong results

### ISSUE THREAD

**Issue by vsilaev** [lukas-krecan/completion-stage#6]
Hello, I did a small test based on net.javacrumbs.completionstage.load.LoadTest with all chaining methods switched to *Async variant + I removed combineEither to avoid uncertainty.

Here is a test:

    
    package net.javacrumbs.completionstage.load;

    import net.javacrumbs.completionstage.CompletableCompletionStage;
    import net.javacrumbs.completionstage.CompletionStageFactory;
    import org.junit.Test;
    
    import java.util.List;
    import java.util.Random;
    import java.util.concurrent.CompletionStage;
    import java.util.concurrent.CopyOnWriteArrayList;
    import java.util.concurrent.ExecutorService;
    import java.util.concurrent.Executors;
    import java.util.concurrent.atomic.AtomicInteger;
    
    import static org.assertj.core.api.Assertions.assertThat;
    
    public class LoadTestAsync {
        private final ExecutorService executor = Executors.newFixedThreadPool(50);
        private final CompletionStageFactory factory = new CompletionStageFactory(executor);
        private final Random random = new Random();
        private final List<String> errors = new CopyOnWriteArrayList<>();
        private final AtomicInteger processed = new AtomicInteger();
    
        @Test
        public void testLoad() throws InterruptedException {
            for (int i = 0; i < 100_000; i++) {
                this.doTest();
            }
            assertThat(errors).isEmpty();
            System.out.println(processed.get());
        }
    
        public void doTest() {
            int value = random.nextInt(Integer.MAX_VALUE / 3);
            delayedCompletionStage(value)
                    .thenCombineAsync(delayedCompletionStage(value), (a, b) -> a + b)
                    .thenApplyAsync(i -> i / 2)
                    .thenApplyAsync(i -> i - value)
                    .thenAcceptAsync(i -> {
                        processed.incrementAndGet();
                        if (i != 0) {
                            errors.add("Error from " + value + " result " + i);
                        }
                    });
        }
    
        private <T> CompletionStage<T> delayedCompletionStage(T value) {
            CompletableCompletionStage<T> completionStage = factory.createCompletionStage();
            completionStage.complete(value);
            return completionStage;
        }
    }

Obviously, `System.out.println(processed.get())` should print a number of the iterations in the for loop deined here:
`
    @Test
    public void testLoad() throws InterruptedException {
        for (int i = 0; i < 100_000; i++) {...}
`

However, starting from some reasonably high number (in my case, approx. 70_000) the test starts to produce random results, like 49731, 51237 etc.

So I guess smth. is broken with async chains under high contention.

Btw, tests hangs if I try smth. like 10_000_000 iterations, while original "synchronus" test works OK with 100_000_000 iterations....

**Comment by vsilaev** [comment]
Ineresting, when I use other thread pool, namely
`private final ExecutorService executor = Executors.newWorkStealingPool(50);`
there is no such issues -- result is correct and test doesn't hangs on extra large number of iterations (100_000_000)...

**Comment by vsilaev** [comment]
Closing issue -- it was my fault, correct test should looks like
    
    package net.javacrumbs.completionstage.load;
    
    import net.javacrumbs.completionstage.CompletableCompletionStage;
    import net.javacrumbs.completionstage.CompletionStageFactory;
    import org.junit.Ignore;
    import org.junit.Test;
    
    import java.util.List;
    import java.util.Random;
    import java.util.concurrent.CompletionStage;
    import java.util.concurrent.CopyOnWriteArrayList;
    import java.util.concurrent.ExecutorService;
    import java.util.concurrent.Executors;
    import java.util.concurrent.atomic.AtomicInteger;
    
    import static org.assertj.core.api.Assertions.assertThat;
    
    public class LoadTestAsync {
        private final ExecutorService executor = Executors.newFixedThreadPool(50);
        private final CompletionStageFactory factory = new CompletionStageFactory(executor);
        private final Random random = new Random();
        private final List<String> errors = new CopyOnWriteArrayList<>();
        private final AtomicInteger processed = new AtomicInteger();
        
        @Test
        //@Ignore
        public void testLoad() throws InterruptedException {
            for (int i = 0; i < 1_000_000; i++) {
                this.doTest().toCompletableFuture().join();
            }
            assertThat(errors).isEmpty();
            System.out.println(processed.get());
        }
    
        public CompletionStage<Void> doTest() {
            int value = random.nextInt(Integer.MAX_VALUE / 3);
            return delayedCompletionStage(value)
                    //.applyToEitherAsync(delayedCompletionStage(value), i -> i * 2)
                    .thenCombineAsync(delayedCompletionStage(value), (a, b) -> a + b)
                    .thenApplyAsync(i -> i / 2)
                    .thenApplyAsync(i -> i - value)
                    .thenAcceptAsync(i -> {
                        processed.getAndIncrement();
                        if (i != 0) {
                            errors.add("Error from " + value + " result " + i);
                        }
                    });
        }
        
        private <T> CompletionStage<T> delayedCompletionStage(T value) {
            CompletableCompletionStage<T> completionStage = factory.createCompletionStage();
            completionStage.complete(value);
            return completionStage;
        }
    }

I.e. it's necessary to wait till tests completion before reporting results

**Comment by lukas-krecan-lt** [comment]
I would call .toCompletableFuture().join() after the for loop, but it's irrelevant. Do you need any help from me? I have been thinking about the Managed use-case and one  possible solution might be to wrap the Executor (or not?)

**Comment by vsilaev** [comment]
No. Just verified myself that ManagedExecutorService handles context switches on it's own:

> Tasks are run in managed threads provided by the Java™ EE Product Provider and are run within the application component context that submitted the task
https://docs.oracle.com/javaee/7/api/javax/enterprise/concurrent/ManagedExecutorService.html

So my only task is to create wrapper for ManagedExecutorService like I did for ExecutorService (though, this time it's more involved). 

Btw, I've checked performance between CallbackRegistry that I included in the pull request and your implementation -- indeed, your implementation is 40-45% faster.

P.S. I were expecting that non-async methods of CompletionStage will be faster than *Async ones, but... The Async version according to my test is approx 15 times slower than synchronous one (745 seconds vs 49 on my hardware).

**Comment by vsilaev** [comment]
Lukáš, could you please make a release with recent changes?

**Comment by lukas-krecan** [comment]
I will release it tonight.



25. 5. 2016 7:37, 7:37, Valery Silaev <notifications@github.com> napsal/a:

**Comment by lukas-krecan** [comment]
Released version 0.0.7, it will take few hours to get to central repo.
