### ISSUE TITLE
Need your approval for derived work / copyrights check

### ISSUE THREAD

**Issue by vsilaev** [lukas-krecan/completion-stage#8]
Lukas, I would like to re-use your work in the form of the modified sources. My library goal is to provide true blocking / IO-bound CompletionStage implementations these are cancellable - i.e. corresponding blocking code may be interrupted. Unfortunately, I can't re-use your code in the binary form -- my tasks requires different execution model. Believe me, I tried my best to extend your classes but give up and re-did core functionality my way, but using your design as a blueprint. So my questions are:

First, and foremost, can you get your explicit permit for this?
Second, is the following copyright notice is sufficient in the related files:
[CallbackRegistry.java](https://github.com/vsilaev/tascalate-concurrent/blob/master/src/main/java/net/tascalate/concurrent/CallbackRegistry.java) - CallbackRegistry in your project
[PromiseAdapter.java](https://github.com/vsilaev/tascalate-concurrent/blob/master/src/main/java/net/tascalate/concurrent/PromiseAdapter.java) - CompletionStageAdapter in your project
[AbstractCompletableTask.java](https://github.com/vsilaev/tascalate-concurrent/blob/master/src/main/java/net/tascalate/concurrent/AbstractCompletableTask.java) - SimpleCompletionStage in your project

Or please provide your version of the header for the aforementioned files.

**Comment by lukas-krecan** [comment]
Hi, no problem, it's licensed under Apache 2 which is quite permissive. I am quite happy that it's useful so feel free to use it however you wish.

**Comment by vsilaev** [comment]
Thank you!
